web:
  port: 3001
  dist: ../web/build/

server:
  port: 8080

db:
  driver-name: mysql
  url: <mysql_username>:<mysql_password>@tcp(<mysql_host>:<mysql_port>)/go-pulsar-manager?charset=utf8mb4&parseTime=True

log:
#  file: app.log # if removed,log in console
  level: info # info,debug,error